### ISSUE TITLE
I get a Fatal error when executing "php artisan migrate --seed"

### ISSUE THREAD

**Issue by pathros** [RaggiTech/laravel-settings#1]
I have added the "use RaggiTech\Laravel\Settings\HasSettings;" inside the models involved.

In Laravel Homestead, there aren't issues when running "php artisan migrate --seed".

However, when running this on a Production server, I get the following error:

```
PHP Fatal error:  Trait 'RaggiTech\Laravel\Settings\HasSettings' not found in /path/to/my/Models/MyModel.php on line xx

   Symfony\Component\ErrorHandler\Error\FatalError 

  Trait 'RaggiTech\Laravel\Settings\HasSettings' not found
```
My model looks as follows:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use RaggiTech\Laravel\Settings\HasSettings;

class MyModel extends Model
{
    use hasSettings; 
...
}
```
How can I fix it?

**Comment by RaggiTech** [comment]
> Trait 'RaggiTech\Laravel\Settings\HasSettings' not found

**This message means that there's a problem in package installation or there's a problem in Composer Autoloader Optimization.**

1. make sure that you have been installed the package on production stage.. and you can check installation with this command 
 ` composer show raggitech/laravel-settings`
if you got any error that's mean the package hasn't been found or there's some problems in composer.

2. if everything is ok try to run `composer dump-autoload -o`

**_because it's working very well for me .. please try this steps now then tell me if still have the same problem._**
